# Generated by Django 4.0.3 on 2022-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Position', models.CharField(max_length=150)),
                ('Tm', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Height_cm', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('PTS', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Salary', models.IntegerField()),
                ('AST', models.DecimalField(decimal_places=3, max_digits=10)),
                ('three_P_perc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('TS_perc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('TOV', models.DecimalField(decimal_places=3, max_digits=10)),
                ('TRB', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
