# Generated by Django 4.1.2 on 2022-11-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('pid', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Position', models.CharField(max_length=150)),
                ('Tm', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Height_cm', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('PTS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Salary', models.IntegerField()),
                ('ATS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('three_P_perc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TS_perc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TOV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TRB', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FavouritePlayer',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playerinfo')),
            ],
            options={
                'unique_together': {('user_id', 'pid')},
            },
        ),
    ]
