# Generated by Django 4.1.2 on 2022-11-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerinfo_user_favouriteplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='ATS',
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='AST',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favouriteplayer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user', unique=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='PTS',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='TOV',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='TRB',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='TS_perc',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='three_P_perc',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
