# Generated by Django 4.1.2 on 2022-11-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_playerinfo_ats_playerinfo_ast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteplayer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
